/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shape.shapevisualization;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author dhananjayawmt
 */
public class MainWindow extends javax.swing.JFrame {

    
    private String shape;
    
    public MainWindow() {
        this.shape = "";
        initComponents();
                              
    }
    
    private boolean isCheckedShape(){
        boolean selected = false;
        if (Triangle.isSelected()
                || Pentagon.isSelected()
                || Circle.isSelected()
                || Rectangle.isSelected()
                || Square.isSelected()
                || Parallelogram.isSelected()
                || Rhombus.isSelected()
                || Hexagon.isSelected()
                || Heptagon.isSelected()
                || Octagon.isSelected()
                || Nonagon.isSelected()
                || Sphere.isSelected()
                || Cylinder.isSelected()
                || Line.isSelected()
                || Arc.isSelected()
                || Ellipse.isSelected()
                || HalfCircle.isSelected()) {
            selected = true;
        }
        
        return selected;
    }

/**
     * Creates new form MainWindow
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapes = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        Octagon = new javax.swing.JRadioButton();
        Square = new javax.swing.JRadioButton();
        Triangle = new javax.swing.JRadioButton();
        Circle = new javax.swing.JRadioButton();
        Rectangle = new javax.swing.JRadioButton();
        Pentagon = new javax.swing.JRadioButton();
        Parallelogram = new javax.swing.JRadioButton();
        Rhombus = new javax.swing.JRadioButton();
        Hexagon = new javax.swing.JRadioButton();
        Nonagon = new javax.swing.JRadioButton();
        HalfCircle = new javax.swing.JRadioButton();
        Heptagon = new javax.swing.JRadioButton();
        Sphere = new javax.swing.JRadioButton();
        Cylinder = new javax.swing.JRadioButton();
        Cube = new javax.swing.JRadioButton();
        Cuboid = new javax.swing.JRadioButton();
        Line = new javax.swing.JRadioButton();
        Arc = new javax.swing.JRadioButton();
        Ellipse = new javax.swing.JRadioButton();
        createbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(110, 30));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setText("SHAPE VISUALIZER");

        kGradientPanel2.setkEndColor(new java.awt.Color(242, 242, 242));
        kGradientPanel2.setkGradientFocus(0);
        kGradientPanel2.setkStartColor(new java.awt.Color(242, 242, 242));

        shapes.add(Octagon);
        Octagon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Octagon.setText("Octagon");
        Octagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctagonActionPerformed(evt);
            }
        });

        shapes.add(Square);
        Square.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Square.setText("Square");
        Square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareActionPerformed(evt);
            }
        });

        shapes.add(Triangle);
        Triangle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Triangle.setText("Traingle");
        Triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TriangleActionPerformed(evt);
            }
        });

        shapes.add(Circle);
        Circle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Circle.setText("Circle");
        Circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CircleActionPerformed(evt);
            }
        });

        shapes.add(Rectangle);
        Rectangle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Rectangle.setText("Rectangle");
        Rectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RectangleActionPerformed(evt);
            }
        });

        shapes.add(Pentagon);
        Pentagon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Pentagon.setText("Pentagon");
        Pentagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PentagonActionPerformed(evt);
            }
        });

        shapes.add(Parallelogram);
        Parallelogram.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Parallelogram.setText("Parallelogram");
        Parallelogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParallelogramActionPerformed(evt);
            }
        });

        shapes.add(Rhombus);
        Rhombus.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Rhombus.setText("Rhombus");
        Rhombus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RhombusActionPerformed(evt);
            }
        });

        shapes.add(Hexagon);
        Hexagon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Hexagon.setText("Hexagon");
        Hexagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexagonActionPerformed(evt);
            }
        });

        shapes.add(Nonagon);
        Nonagon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Nonagon.setText("Nonagon");
        Nonagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NonagonActionPerformed(evt);
            }
        });

        shapes.add(HalfCircle);
        HalfCircle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        HalfCircle.setText("Half Circle");
        HalfCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HalfCircleActionPerformed(evt);
            }
        });

        shapes.add(Heptagon);
        Heptagon.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Heptagon.setText("Heptagon");
        Heptagon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeptagonActionPerformed(evt);
            }
        });

        shapes.add(Sphere);
        Sphere.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Sphere.setText("Sphere");
        Sphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SphereActionPerformed(evt);
            }
        });

        shapes.add(Cylinder);
        Cylinder.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Cylinder.setText("Cylinder");
        Cylinder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CylinderActionPerformed(evt);
            }
        });

        shapes.add(Cube);
        Cube.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Cube.setText("Cube");

        shapes.add(Cuboid);
        Cuboid.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Cuboid.setText("Cuboid");

        shapes.add(Line);
        Line.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Line.setText("Line");
        Line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineActionPerformed(evt);
            }
        });

        shapes.add(Arc);
        Arc.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Arc.setText("Arc");
        Arc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArcActionPerformed(evt);
            }
        });

        shapes.add(Ellipse);
        Ellipse.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Ellipse.setText("Ellipse");
        Ellipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EllipseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Square)
                    .addComponent(Circle)
                    .addComponent(Triangle)
                    .addComponent(HalfCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Rectangle)
                    .addComponent(Parallelogram)
                    .addComponent(Rhombus)
                    .addComponent(Pentagon))
                .addGap(158, 158, 158)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hexagon)
                    .addComponent(Heptagon)
                    .addComponent(Nonagon)
                    .addComponent(Octagon))
                .addGap(113, 113, 113)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sphere)
                    .addComponent(Cube, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cuboid)
                    .addComponent(Cylinder))
                .addGap(91, 91, 91)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Line)
                    .addComponent(Arc)
                    .addComponent(Ellipse))
                .addGap(103, 103, 103))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Rectangle)
                        .addComponent(Triangle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Hexagon)
                    .addComponent(Sphere)
                    .addComponent(Line))
                .addGap(60, 60, 60)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Parallelogram, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Circle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Heptagon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Cube, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arc, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Rhombus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HalfCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cuboid, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Octagon))
                    .addComponent(Ellipse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Pentagon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Square, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(Nonagon)
                    .addComponent(Cylinder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );

        createbtn.setBackground(new java.awt.Color(255, 0, 51));
        createbtn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        createbtn.setText("Create Shape");
        createbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Choose Shape");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(529, 529, 529))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1118, Short.MAX_VALUE)))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel1Layout.createSequentialGroup()
                    .addGap(124, 124, 124)
                    .addComponent(jLabel4)
                    .addContainerGap(613, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HalfCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HalfCircleActionPerformed
        shape = "HalfCircle";
    }//GEN-LAST:event_HalfCircleActionPerformed

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        if (this.isCheckedShape()) {
            OptionWindow optionWindow = new OptionWindow(shape);
            optionWindow.setVisible(true);        
            dispose();
        }
        else {
            
        }
    }//GEN-LAST:event_createbtnActionPerformed

    private void CircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CircleActionPerformed
        shape = "Circle";
    }//GEN-LAST:event_CircleActionPerformed

    private void PentagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PentagonActionPerformed
        shape = "Pentagon";
    }//GEN-LAST:event_PentagonActionPerformed

    private void RectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RectangleActionPerformed
        shape = "Rectangle";
    }//GEN-LAST:event_RectangleActionPerformed

    private void SquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareActionPerformed
        shape = "Square";
    }//GEN-LAST:event_SquareActionPerformed

    private void TriangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TriangleActionPerformed
        shape = "Triangle";
    }//GEN-LAST:event_TriangleActionPerformed

    private void ParallelogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParallelogramActionPerformed
        shape = "Parallelogram";
    }//GEN-LAST:event_ParallelogramActionPerformed

    private void RhombusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RhombusActionPerformed
        shape = "Rhombus";
    }//GEN-LAST:event_RhombusActionPerformed

    private void HexagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexagonActionPerformed
        shape = "Hexagon";
    }//GEN-LAST:event_HexagonActionPerformed

    private void OctagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctagonActionPerformed
        shape = "Octagon";
    }//GEN-LAST:event_OctagonActionPerformed

    private void HeptagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeptagonActionPerformed
        shape = "Heptagon";
    }//GEN-LAST:event_HeptagonActionPerformed

    private void NonagonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NonagonActionPerformed
        shape = "Nonagon";
    }//GEN-LAST:event_NonagonActionPerformed

    private void SphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SphereActionPerformed
        shape = "Sphere";
    }//GEN-LAST:event_SphereActionPerformed

    private void CylinderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CylinderActionPerformed
        shape = "Cylinder";
    }//GEN-LAST:event_CylinderActionPerformed

    private void LineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineActionPerformed
        shape = "Line";
    }//GEN-LAST:event_LineActionPerformed

    private void ArcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArcActionPerformed
        shape = "Arc";
    }//GEN-LAST:event_ArcActionPerformed

    private void EllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EllipseActionPerformed
        shape = "Ellipse";
    }//GEN-LAST:event_EllipseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Arc;
    private javax.swing.JRadioButton Circle;
    private javax.swing.JRadioButton Cube;
    private javax.swing.JRadioButton Cuboid;
    private javax.swing.JRadioButton Cylinder;
    private javax.swing.JRadioButton Ellipse;
    private javax.swing.JRadioButton HalfCircle;
    private javax.swing.JRadioButton Heptagon;
    private javax.swing.JRadioButton Hexagon;
    private javax.swing.JRadioButton Line;
    private javax.swing.JRadioButton Nonagon;
    private javax.swing.JRadioButton Octagon;
    private javax.swing.JRadioButton Parallelogram;
    private javax.swing.JRadioButton Pentagon;
    private javax.swing.JRadioButton Rectangle;
    private javax.swing.JRadioButton Rhombus;
    private javax.swing.JRadioButton Sphere;
    private javax.swing.JRadioButton Square;
    private javax.swing.JRadioButton Triangle;
    private javax.swing.JButton createbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.ButtonGroup shapes;
    // End of variables declaration//GEN-END:variables
}
